// Comprehensive Academic Courses Dataset & Stream-Adjacency Matrix
// My Student Academia Ecosystem

export interface CourseCatalogItem {
  id: string;
  code: string;
  title: string;
  description: string;
  credits: number;
  difficulty: "Introductory" | "Intermediate" | "Advanced" | "Capstone";
  primaryStream: string;
  adjacentStreams: string[];
  department: {
    id: string;
    code: string;
    name: string;
  };
  instructor: {
    name: string;
    title: string;
    avatar: string;
  };
  slotCode: string;
  scheduleDays: string;
  scheduleTime: string;
  room: string;
  capacity: number;
  enrolledCount: number;
  waitlistCount: number;
  syllabus: string[];
  tags: string[];
  isLabIncluded?: boolean;
}

// ✦ STREAM ADJACENCY MATRIX ✦
// Defines which neighboring streams are intellectually adjacent for cross-disciplinary electives
export const STREAM_ADJACENCY_MAP: Record<string, string[]> = {
  "Computer Science & Engineering": [
    "Artificial Intelligence & Data Science",
    "Cybersecurity, Cloud & Ethical Hacking",
    "Electrical, Electronics & VLSI",
    "UI/UX Design, HCI & Interactive Media",
    "Business, Fintech & Quantitative Finance",
  ],
  "Artificial Intelligence & Data Science": [
    "Computer Science & Engineering",
    "Business, Fintech & Quantitative Finance",
    "Biotechnology, Bioinformatics & Genetics",
    "Electrical, Electronics & VLSI",
    "Medical Sciences & Health Informatics",
    "UI/UX Design, HCI & Interactive Media",
  ],
  "Electrical, Electronics & VLSI": [
    "Computer Science & Engineering",
    "Mechanical & Aerospace Engineering",
    "Artificial Intelligence & Data Science",
    "Cybersecurity, Cloud & Ethical Hacking",
    "Chemical Engineering & Nanotechnology",
  ],
  "Mechanical & Aerospace Engineering": [
    "Electrical, Electronics & VLSI",
    "Civil, Environmental & Structural Engineering",
    "Chemical Engineering & Nanotechnology",
    "Artificial Intelligence & Data Science",
  ],
  "Civil, Environmental & Structural Engineering": [
    "Mechanical & Aerospace Engineering",
    "Chemical Engineering & Nanotechnology",
    "UI/UX Design, HCI & Interactive Media",
    "Legal Studies, Cyber Law & Tech Policy",
  ],
  "Biotechnology, Bioinformatics & Genetics": [
    "Artificial Intelligence & Data Science",
    "Medical Sciences & Health Informatics",
    "Chemical Engineering & Nanotechnology",
    "Computer Science & Engineering",
  ],
  "Business, Fintech & Quantitative Finance": [
    "Computer Science & Engineering",
    "Artificial Intelligence & Data Science",
    "Cybersecurity, Cloud & Ethical Hacking",
    "Legal Studies, Cyber Law & Tech Policy",
    "UI/UX Design, HCI & Interactive Media",
  ],
  "UI/UX Design, HCI & Interactive Media": [
    "Computer Science & Engineering",
    "Artificial Intelligence & Data Science",
    "Business, Fintech & Quantitative Finance",
    "Civil, Environmental & Structural Engineering",
  ],
  "Cybersecurity, Cloud & Ethical Hacking": [
    "Computer Science & Engineering",
    "Legal Studies, Cyber Law & Tech Policy",
    "Electrical, Electronics & VLSI",
    "Business, Fintech & Quantitative Finance",
  ],
  "Chemical Engineering & Nanotechnology": [
    "Biotechnology, Bioinformatics & Genetics",
    "Mechanical & Aerospace Engineering",
    "Civil, Environmental & Structural Engineering",
    "Medical Sciences & Health Informatics",
  ],
  "Legal Studies, Cyber Law & Tech Policy": [
    "Cybersecurity, Cloud & Ethical Hacking",
    "Business, Fintech & Quantitative Finance",
    "Artificial Intelligence & Data Science",
    "Civil, Environmental & Structural Engineering",
  ],
  "Medical Sciences & Health Informatics": [
    "Biotechnology, Bioinformatics & Genetics",
    "Artificial Intelligence & Data Science",
    "Computer Science & Engineering",
    "Chemical Engineering & Nanotechnology",
  ],
};

// ✦ EXPANDED REALISTIC UNIVERSITY COURSES ACROSS 12 STREAMS ✦
export const EXPANDED_COURSE_CATALOG: CourseCatalogItem[] = [
  // ─── 1. COMPUTER SCIENCE & DISTRIBUTED SYSTEMS ───
  {
    id: "course-cs-101",
    code: "CS101",
    title: "Computational Thinking & Algorithm Design",
    description: "Foundations of procedural programming, asymptotic complexity analysis, memory models, and algorithmic problem-solving in Python & C++.",
    credits: 4,
    difficulty: "Introductory",
    primaryStream: "Computer Science & Engineering",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Electrical, Electronics & VLSI", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Vikram Sethi", title: "Professor of Algorithms", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A1",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "09:00 AM - 10:30 AM",
    room: "Turing Hall 101",
    capacity: 120,
    enrolledCount: 94,
    waitlistCount: 0,
    syllabus: ["Big-O Complexity & Recursion", "Divide & Conquer Sorting", "Dynamic Memory & Pointers", "Stacks, Queues, Hash Tables"],
    tags: ["Algorithms", "Python", "Data Structures", "Core CS"],
    isLabIncluded: true,
  },
  {
    id: "course-cs-201",
    code: "CS201",
    title: "Data Structures & High-Performance Computing",
    description: "Advanced graph theory, self-balancing search trees (AVL/Red-Black), spatial trees, concurrency patterns, and cache-oblivious algorithms.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Computer Science & Engineering",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Cybersecurity, Cloud & Ethical Hacking", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Ananya Roy", title: "Distinguished Chair of Systems", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "10:45 AM - 12:15 PM",
    room: "Knuth Auditorium",
    capacity: 100,
    enrolledCount: 88,
    waitlistCount: 4,
    syllabus: ["Balanced Binary Search Trees", "Graph Traversal & Shortest Path", "Disjoint Set Union & MST", "Multi-Threaded Concurrency"],
    tags: ["Graphs", "Data Structures", "C++", "High Performance"],
  },
  {
    id: "course-cs-301",
    code: "CS301",
    title: "Modern Full-Stack Architecture & Cloud Systems",
    description: "Reactive web architectures, micro-frontends, event-driven backends, WebSockets, Kafka streaming, containerization with Docker, and Kubernetes deployment.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Computer Science & Engineering",
    adjacentStreams: ["UI/UX Design, HCI & Interactive Media", "Cybersecurity, Cloud & Ethical Hacking", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Prof. Rohan Mukherjee", title: "Lead Systems Architect", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C2",
    scheduleDays: "Mon, Wed",
    scheduleTime: "02:00 PM - 03:30 PM",
    room: "Cloud Lab 304",
    capacity: 80,
    enrolledCount: 76,
    waitlistCount: 2,
    syllabus: ["Next.js & Server Components", "Distributed Caching (Redis)", "Event Streaming (Kafka)", "Docker & Kubernetes Orchestration"],
    tags: ["Full Stack", "Cloud", "Kubernetes", "Web Architecture"],
    isLabIncluded: true,
  },
  {
    id: "course-cs-310",
    code: "CS310",
    title: "Distributed Systems & Consensus Protocols",
    description: "CAP theorem, Raft & Paxos consensus protocols, Byzantine fault tolerance, distributed transactions (2PC/Saga), and peer-to-peer storage architectures.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Computer Science & Engineering",
    adjacentStreams: ["Cybersecurity, Cloud & Ethical Hacking", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Emily Reed", title: "Fellow of Distributed Computing", avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Systems Seminar 202",
    capacity: 65,
    enrolledCount: 58,
    waitlistCount: 0,
    syllabus: ["Raft & Paxos Consensus", "Vector Clocks & Distributed Tracing", "Vector Databases & Sharding", "Fault Tolerance in Large Clusters"],
    tags: ["Distributed Systems", "Raft", "Consensus", "Backend Core"],
  },

  // ─── 2. ARTIFICIAL INTELLIGENCE & DATA SCIENCE ───
  {
    id: "course-ai-301",
    code: "AI301",
    title: "Machine Learning & Statistical Pattern Recognition",
    description: "Supervised and unsupervised learning, empirical risk minimization, gradient boosting (XGBoost), kernel methods, SVMs, PCA, and probabilistic clustering.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Artificial Intelligence & Data Science",
    adjacentStreams: ["Computer Science & Engineering", "Business, Fintech & Quantitative Finance", "Biotechnology, Bioinformatics & Genetics"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Priya Deshmukh", title: "Principal AI Scientist", avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A2",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "11:00 AM - 12:30 PM",
    room: "Neural Lab 402",
    capacity: 110,
    enrolledCount: 104,
    waitlistCount: 6,
    syllabus: ["Loss Functions & Convex Optimization", "Decision Trees & Ensemble Boosting", "Support Vector Machines", "Unsupervised Clustering & t-SNE"],
    tags: ["Machine Learning", "Python", "Data Science", "Optimization"],
    isLabIncluded: true,
  },
  {
    id: "course-ai-402",
    code: "AI402",
    title: "Deep Learning & Neural Network Architectures",
    description: "Backpropagation dynamics, Transformers, Self-Attention, CNNs, Recurrent architectures, Autoencoders, and PyTorch multi-GPU model training.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Artificial Intelligence & Data Science",
    adjacentStreams: ["Computer Science & Engineering", "Medical Sciences & Health Informatics", "Electrical, Electronics & VLSI"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Karl Schmidt", title: "Director of Deep Learning Lab", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "01:30 PM - 03:00 PM",
    room: "Compute Cluster Lab 5",
    capacity: 90,
    enrolledCount: 89,
    waitlistCount: 8,
    syllabus: ["Transformers & Multi-Head Attention", "Vision Transformers (ViT)", "Diffusion Models & Generative Priors", "PyTorch Distributed Data Parallel"],
    tags: ["Deep Learning", "PyTorch", "Transformers", "Neural Networks"],
    isLabIncluded: true,
  },
  {
    id: "course-ai-405",
    code: "AI405",
    title: "Computer Vision & Spatial 3D Intelligence",
    description: "Object detection (YOLO/R-CNN), semantic segmentation, Neural Radiance Fields (NeRF), 3D Gaussian Splatting, and visual SLAM for autonomous robotics.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Artificial Intelligence & Data Science",
    adjacentStreams: ["Mechanical & Aerospace Engineering", "UI/UX Design, HCI & Interactive Media", "Electrical, Electronics & VLSI"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Chen Wei", title: "Professor of Spatial Computing", avatar: "https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C1",
    scheduleDays: "Mon, Wed",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Vision Studio 108",
    capacity: 75,
    enrolledCount: 68,
    waitlistCount: 0,
    syllabus: ["Feature Extraction & Homography", "Real-Time Object Detection", "Neural Radiance Fields (NeRF)", "Visual Odometry & SLAM"],
    tags: ["Computer Vision", "NeRF", "3D Gaussian Splatting", "Robotics Vision"],
  },
  {
    id: "course-ai-408",
    code: "AI408",
    title: "Generative AI, Large Language Models & Agentic Systems",
    description: "LLM pre-training, RLHF alignment, Retrieval-Augmented Generation (RAG), Autonomous Agent orchestration (LangGraph, MCP), and reasoning loops.",
    credits: 4,
    difficulty: "Capstone",
    primaryStream: "Artificial Intelligence & Data Science",
    adjacentStreams: ["Computer Science & Engineering", "Business, Fintech & Quantitative Finance", "Legal Studies, Cyber Law & Tech Policy"],
    department: { id: "dept-cs", code: "CS", name: "Computer Science & AI" },
    instructor: { name: "Dr. Priya Deshmukh", title: "Principal AI Scientist", avatar: "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "05:30 PM - 07:00 PM",
    room: "AI Innovation Pavilion",
    capacity: 85,
    enrolledCount: 82,
    waitlistCount: 12,
    syllabus: ["Pre-training & LoRA Fine-Tuning", "Vector Search & Hybrid RAG", "Multi-Agent Protocol Orchestration", "Safety, Alignment & Tool Calling"],
    tags: ["Generative AI", "LLMs", "RAG", "Agentic Systems"],
    isLabIncluded: true,
  },

  // ─── 3. ELECTRICAL, ELECTRONICS & VLSI ───
  {
    id: "course-ece-201",
    code: "ECE201",
    title: "Digital Logic & Microprocessor Architecture",
    description: "Boolean algebra, sequential state machines, RISC-V ISA design, pipelining, cache memory hierarchies, and hardware description in Verilog.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Electrical, Electronics & VLSI",
    adjacentStreams: ["Computer Science & Engineering", "Mechanical & Aerospace Engineering"],
    department: { id: "dept-ece", code: "ECE", name: "Electrical & Electronics" },
    instructor: { name: "Dr. Rajeshwar Rao", title: "Chair of Semiconductor Research", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A1",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "09:00 AM - 10:30 AM",
    room: "Silicon Lab 102",
    capacity: 80,
    enrolledCount: 71,
    waitlistCount: 0,
    syllabus: ["Verilog HDL & Synthesis", "RISC-V 5-Stage Pipelining", "Hazard Detection & Forwarding", "Cache Coherence Protocols"],
    tags: ["Digital Logic", "RISC-V", "Verilog", "Hardware Architecture"],
    isLabIncluded: true,
  },
  {
    id: "course-ece-202",
    code: "ECE202",
    title: "Embedded IoT Systems & Real-Time Operating Systems",
    description: "ARM Cortex-M firmware engineering, FreeRTOS scheduling, sensor buses (I2C/SPI/CAN), low-power wireless (BLE/Zigbee/LoRaWAN), and Edge ML.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Electrical, Electronics & VLSI",
    adjacentStreams: ["Computer Science & Engineering", "Mechanical & Aerospace Engineering", "Artificial Intelligence & Data Science"],
    department: { id: "dept-ece", code: "ECE", name: "Electrical & Electronics" },
    instructor: { name: "Prof. Arvind Nambiar", title: "Associate Professor of IoT", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "10:45 AM - 12:15 PM",
    room: "Embedded Systems Suite",
    capacity: 70,
    enrolledCount: 65,
    waitlistCount: 1,
    syllabus: ["FreeRTOS Task Scheduling & Mutexes", "DMA & Interrupt Service Routines", "CAN Bus for Automotive Protocols", "TinyML on Microcontrollers"],
    tags: ["Embedded", "IoT", "FreeRTOS", "ARM Cortex"],
    isLabIncluded: true,
  },
  {
    id: "course-ece-305",
    code: "ECE305",
    title: "VLSI Chip Design, Synthesis & Tapeout",
    description: "CMOS layout, static timing analysis (STA), clock tree synthesis, place-and-route with Cadence/Synopsys, and physical design verification.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Electrical, Electronics & VLSI",
    adjacentStreams: ["Computer Science & Engineering", "Chemical Engineering & Nanotechnology"],
    department: { id: "dept-ece", code: "ECE", name: "Electrical & Electronics" },
    instructor: { name: "Dr. Rajeshwar Rao", title: "Chair of Semiconductor Research", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C2",
    scheduleDays: "Mon, Wed",
    scheduleTime: "02:00 PM - 03:30 PM",
    room: "VLSI Cleanroom 201",
    capacity: 50,
    enrolledCount: 47,
    waitlistCount: 0,
    syllabus: ["CMOS Inverter Dynamics & Propagation", "Static Timing Analysis (STA)", "Clock Tree Synthesis & Skew", "Design For Testability (DFT)"],
    tags: ["VLSI", "Semiconductors", "Physical Design", "Cadence"],
  },
  {
    id: "course-rob-401",
    code: "ROB401",
    title: "Autonomous Robotics, Kinematics & ROS 2",
    description: "Forward and inverse kinematics, trajectory planning, PID and MPC motor control, LiDAR mapping, and ROS 2 middleware architecture.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Electrical, Electronics & VLSI",
    adjacentStreams: ["Mechanical & Aerospace Engineering", "Artificial Intelligence & Data Science", "Computer Science & Engineering"],
    department: { id: "dept-ece", code: "ECE", name: "Electrical & Electronics" },
    instructor: { name: "Prof. Arvind Nambiar", title: "Associate Professor of IoT", avatar: "https://images.unsplash.com/photo-1519085360753-af0119f7cbe7?q=80&w=200&auto=format&fit=crop" },
    slotCode: "E1",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "08:00 AM - 09:30 AM",
    room: "Robotics Arena & Lab",
    capacity: 60,
    enrolledCount: 58,
    waitlistCount: 3,
    syllabus: ["Denavit-Hartenberg (DH) Parameters", "Inverse Kinematics with Quaternions", "ROS 2 Nodes, Topics & Actions", "Model Predictive Control (MPC)"],
    tags: ["Robotics", "ROS2", "Kinematics", "Autonomous Systems"],
    isLabIncluded: true,
  },

  // ─── 4. MECHANICAL & AEROSPACE ENGINEERING ───
  {
    id: "course-me-101",
    code: "ME101",
    title: "Thermodynamics & Continuum Mechanics",
    description: "First and second laws of thermodynamics, entropy generation, Rankine and Brayton cycles, stress-strain tensors, and fluid statics.",
    credits: 4,
    difficulty: "Introductory",
    primaryStream: "Mechanical & Aerospace Engineering",
    adjacentStreams: ["Chemical Engineering & Nanotechnology", "Civil, Environmental & Structural Engineering", "Electrical, Electronics & VLSI"],
    department: { id: "dept-me", code: "ME", name: "Mechanical Engineering" },
    instructor: { name: "Dr. Suresh Kulkarni", title: "Professor of Thermal Systems", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A2",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "11:00 AM - 12:30 PM",
    room: "Carnot Hall 104",
    capacity: 90,
    enrolledCount: 82,
    waitlistCount: 0,
    syllabus: ["Closed & Open Control Volumes", "Carnot & Rankine Power Cycles", "Exergy & Second-Law Efficiency", "Stress & Strain Transformation Tensors"],
    tags: ["Thermodynamics", "Mechanics", "Energy Systems"],
  },
  {
    id: "course-me-204",
    code: "ME204",
    title: "Generative CAD/CAM, FEA & Additive Manufacturing",
    description: "Parametric 3D solid modeling in SolidWorks/Fusion360, finite element stress analysis (FEA), topological optimization, and 5-axis CNC machining.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Mechanical & Aerospace Engineering",
    adjacentStreams: ["UI/UX Design, HCI & Interactive Media", "Civil, Environmental & Structural Engineering"],
    department: { id: "dept-me", code: "ME", name: "Mechanical Engineering" },
    instructor: { name: "Prof. Tanya Sen", title: "Lead Manufacturing Scientist", avatar: "https://images.unsplash.com/photo-1573496799652-408c2ac9fe98?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "01:30 PM - 03:00 PM",
    room: "Advanced Fab Lab",
    capacity: 65,
    enrolledCount: 61,
    waitlistCount: 2,
    syllabus: ["Parametric Surface Modeling", "Linear Static Finite Element Analysis", "Topological Mass Optimization", "G-Code Generation & CNC Machining"],
    tags: ["CAD", "CAM", "FEA", "SolidWorks", "3D Printing"],
    isLabIncluded: true,
  },
  {
    id: "course-aero-401",
    code: "AERO401",
    title: "Aerodynamics, Hypersonic Flow & Orbital Mechanics",
    description: "Compressible aerodynamics, shock waves, Prandtl-Meyer expansion, rocket propulsion equations, and two-body Keplerian orbital mechanics.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Mechanical & Aerospace Engineering",
    adjacentStreams: ["Electrical, Electronics & VLSI", "Artificial Intelligence & Data Science"],
    department: { id: "dept-me", code: "ME", name: "Mechanical Engineering" },
    instructor: { name: "Dr. Suresh Kulkarni", title: "Professor of Thermal Systems", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C1",
    scheduleDays: "Mon, Wed",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Propulsion Hangar 3",
    capacity: 55,
    enrolledCount: 52,
    waitlistCount: 1,
    syllabus: ["Subsonic & Supersonic Airfoil Theory", "Oblique Shocks & Expansion Fans", "Rocket Thrust & Specific Impulse", "Orbital Transfers (Hohmann / Bi-elliptic)"],
    tags: ["Aerospace", "Propulsion", "Orbital Mechanics", "Flight Dynamics"],
  },

  // ─── 5. BUSINESS, FINTECH & QUANTITATIVE FINANCE ───
  {
    id: "course-fin-101",
    code: "FIN101",
    title: "Corporate Finance, Asset Pricing & Valuation",
    description: "Discounted cash flow (DCF) modeling, Capital Asset Pricing Model (CAPM), WACC estimation, capital structure, and M&A transaction analysis.",
    credits: 3,
    difficulty: "Introductory",
    primaryStream: "Business, Fintech & Quantitative Finance",
    adjacentStreams: ["Computer Science & Engineering", "Legal Studies, Cyber Law & Tech Policy"],
    department: { id: "dept-fin", code: "FIN", name: "Fintech & Management" },
    instructor: { name: "Prof. Kabir Mehra", title: "Managing Director of FinTech Lab", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "10:45 AM - 12:15 PM",
    room: "Bloomberg Finance Suite",
    capacity: 90,
    enrolledCount: 84,
    waitlistCount: 0,
    syllabus: ["Time Value of Money & DCF", "Risk, Return & Modern Portfolio Theory", "WACC & Optimal Capital Structure", "Multiples & Comparable Valuation"],
    tags: ["Finance", "Valuation", "DCF", "Economics"],
  },
  {
    id: "course-fin-305",
    code: "FIN305",
    title: "Quantitative Trading & Algorithmic Execution",
    description: "Statistical arbitrage, order book microstructure, Black-Scholes options pricing, high-frequency backtesting in Python/C++, and risk factor models.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Business, Fintech & Quantitative Finance",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Computer Science & Engineering"],
    department: { id: "dept-fin", code: "FIN", name: "Fintech & Management" },
    instructor: { name: "Dr. Alok Nath", title: "Chief Quant Researcher", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C2",
    scheduleDays: "Mon, Wed",
    scheduleTime: "02:00 PM - 03:30 PM",
    room: "Trading Floor Terminal",
    capacity: 75,
    enrolledCount: 74,
    waitlistCount: 9,
    syllabus: ["Limit Order Book Microstructure", "Pairs Trading & Cointegration", "Black-Scholes-Merton Options Model", "Alpha Generation & Backtest Slippage"],
    tags: ["Quant Finance", "Algo Trading", "Python", "Derivatives"],
    isLabIncluded: true,
  },
  {
    id: "course-fin-402",
    code: "FIN402",
    title: "Decentralized Finance (DeFi) & Blockchain Protocols",
    description: "Smart contract engineering in Solidity, Automated Market Makers (Uniswap AMM formulas), lending pools (Aave), cross-chain bridges, and MEV extraction.",
    credits: 3,
    difficulty: "Advanced",
    primaryStream: "Business, Fintech & Quantitative Finance",
    adjacentStreams: ["Computer Science & Engineering", "Cybersecurity, Cloud & Ethical Hacking", "Legal Studies, Cyber Law & Tech Policy"],
    department: { id: "dept-fin", code: "FIN", name: "Fintech & Management" },
    instructor: { name: "Prof. Kabir Mehra", title: "Managing Director of FinTech Lab", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Crypto Economy Lab",
    capacity: 65,
    enrolledCount: 60,
    waitlistCount: 0,
    syllabus: ["Solidity Security & Reentrancy", "Constant Product AMM Mathematics", "Collateralized Debt Positions (CDPs)", "Maximal Extractable Value (MEV)"],
    tags: ["DeFi", "Blockchain", "Smart Contracts", "Fintech"],
  },

  // ─── 6. BIOTECHNOLOGY & BIOINFORMATICS ───
  {
    id: "course-bio-101",
    code: "BIO101",
    title: "Molecular Genetics & Cellular Biochemistry",
    description: "DNA replication, transcription, translational regulation, enzyme kinetics (Michaelis-Menten), metabolic pathways, and signal transduction cascades.",
    credits: 4,
    difficulty: "Introductory",
    primaryStream: "Biotechnology, Bioinformatics & Genetics",
    adjacentStreams: ["Medical Sciences & Health Informatics", "Chemical Engineering & Nanotechnology"],
    department: { id: "dept-bio", code: "BIO", name: "Biotechnology & Health" },
    instructor: { name: "Dr. Meenakshi Sundaram", title: "Professor of Molecular Biology", avatar: "https://images.unsplash.com/photo-1594824813589-58ec71752b07?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A1",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "09:00 AM - 10:30 AM",
    room: "Bio-Genetics Lab 1",
    capacity: 80,
    enrolledCount: 72,
    waitlistCount: 0,
    syllabus: ["Central Dogma of Molecular Biology", "Enzyme Kinetics & Allosteric Control", "Signal Transduction & GPCR Pathways", "Recombinant DNA Techniques"],
    tags: ["Genetics", "Biochemistry", "Molecular Biology"],
    isLabIncluded: true,
  },
  {
    id: "course-bio-203",
    code: "BIO203",
    title: "Computational Genomics & Next-Gen Sequencing (NGS)",
    description: "FASTA/FASTQ sequence alignment (BLAST, Bowtie), genome assembly, variant calling pipelines, RNA-Seq transcriptomics, and AlphaFold protein folding.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Biotechnology, Bioinformatics & Genetics",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Computer Science & Engineering", "Medical Sciences & Health Informatics"],
    department: { id: "dept-bio", code: "BIO", name: "Biotechnology & Health" },
    instructor: { name: "Dr. David Thorne", title: "Head of Computational Genomics", avatar: "https://images.unsplash.com/photo-1537368910025-700350fe46c7?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C1",
    scheduleDays: "Mon, Wed",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Bioinformatics Cluster 3",
    capacity: 65,
    enrolledCount: 62,
    waitlistCount: 3,
    syllabus: ["Burrows-Wheeler Transform & Alignment", "Variant Calling (VCF & GATK)", "RNA-Seq Differential Expression", "AlphaFold 3D Protein Structure Inference"],
    tags: ["Bioinformatics", "Genomics", "Python", "AlphaFold"],
    isLabIncluded: true,
  },
  {
    id: "course-bio-305",
    code: "BIO305",
    title: "CRISPR Gene Editing & Synthetic Biology",
    description: "Cas9/Cas12 endonuclease mechanisms, guide RNA design, prime editing, metabolic pathway re-engineering, and ethical biocontainment frameworks.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Biotechnology, Bioinformatics & Genetics",
    adjacentStreams: ["Medical Sciences & Health Informatics", "Legal Studies, Cyber Law & Tech Policy"],
    department: { id: "dept-bio", code: "BIO", name: "Biotechnology & Health" },
    instructor: { name: "Dr. Meenakshi Sundaram", title: "Professor of Molecular Biology", avatar: "https://images.unsplash.com/photo-1594824813589-58ec71752b07?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "05:30 PM - 07:00 PM",
    room: "Synthetic Biology Cleanroom",
    capacity: 50,
    enrolledCount: 48,
    waitlistCount: 0,
    syllabus: ["CRISPR-Cas9 Cleavage Dynamics", "Base Editing & Prime Editing Protocols", "Synthetic Gene Circuits & Switches", "Bioethics & Dual-Use Technology"],
    tags: ["CRISPR", "Gene Editing", "Synthetic Biology"],
  },

  // ─── 7. UI/UX DESIGN, HCI & SPATIAL COMPUTING ───
  {
    id: "course-des-101",
    code: "DES101",
    title: "Design Systems, Visual Hierarchy & Typography",
    description: "Atomic design theory, typographic scales, color psychology, accessible contrast (WCAG AAA), component tokenization, and Figma auto-layout mastery.",
    credits: 3,
    difficulty: "Introductory",
    primaryStream: "UI/UX Design, HCI & Interactive Media",
    adjacentStreams: ["Computer Science & Engineering", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-des", code: "DES", name: "Design & Interactive Media" },
    instructor: { name: "Prof. Elena Rostova", title: "Head of Design Systems", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "01:30 PM - 03:00 PM",
    room: "Studio Arts 205",
    capacity: 70,
    enrolledCount: 67,
    waitlistCount: 0,
    syllabus: ["Atomic Design & Component Libraries", "Modular Typographic Scales", "Accessibility & High-Contrast Design", "Design Tokens & Figma Dev Mode"],
    tags: ["UI/UX", "Figma", "Design Systems", "Typography"],
  },
  {
    id: "course-des-105",
    code: "DES105",
    title: "Cognitive Psychology, Usability & User Research",
    description: "Hick's Law, Fitts's Law, cognitive load reduction, qualitative user interviews, eye-tracking heatmap analytics, and A/B hypothesis testing.",
    credits: 3,
    difficulty: "Intermediate",
    primaryStream: "UI/UX Design, HCI & Interactive Media",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-des", code: "DES", name: "Design & Interactive Media" },
    instructor: { name: "Dr. Maya Kapoor", title: "Cognitive Ergonomics Researcher", avatar: "https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C1",
    scheduleDays: "Mon, Wed",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Usability Testing Suite",
    capacity: 60,
    enrolledCount: 58,
    waitlistCount: 2,
    syllabus: ["Mental Models & Cognitive Biases", "User Journey Mapping & Personas", "Usability Testing & Task Completion Rate", "A/B Multivariate Statistical Testing"],
    tags: ["UX Research", "Cognitive Science", "Usability"],
  },
  {
    id: "course-des-302",
    code: "DES302",
    title: "AR/VR Spatial Computing & 3D Interaction Design",
    description: "Spatial audio design, 6-DoF hand-tracking gestures in visionOS / Unity, immersive physics, shaders, and real-time WebGL experiences in Three.js.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "UI/UX Design, HCI & Interactive Media",
    adjacentStreams: ["Computer Science & Engineering", "Artificial Intelligence & Data Science"],
    department: { id: "dept-des", code: "DES", name: "Design & Interactive Media" },
    instructor: { name: "Prof. Elena Rostova", title: "Head of Design Systems", avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "05:30 PM - 07:00 PM",
    room: "Spatial Reality Holodeck",
    capacity: 50,
    enrolledCount: 49,
    waitlistCount: 4,
    syllabus: ["Spatial UI Principles (visionOS)", "Three.js Shaders & PBR Materials", "6-DoF Hand Tracking & Haptics", "Interactive WebGL Experiences"],
    tags: ["Spatial Computing", "Three.js", "AR/VR", "WebGL"],
    isLabIncluded: true,
  },

  // ─── 8. CYBERSECURITY, CLOUD & ETHICAL HACKING ───
  {
    id: "course-cyb-201",
    code: "CYB201",
    title: "Network Security, Applied Cryptography & PKI",
    description: "Symmetric (AES-GCM) & asymmetric (RSA, ECC, Post-Quantum Dilithium) ciphers, TLS 1.3 handshakes, PKI certificate authorities, and VPN tunnels.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Cybersecurity, Cloud & Ethical Hacking",
    adjacentStreams: ["Computer Science & Engineering", "Legal Studies, Cyber Law & Tech Policy"],
    department: { id: "dept-cyb", code: "CYB", name: "Cybersecurity & Cloud" },
    instructor: { name: "Dr. Marcus Vance", title: "Director of Cyber Defense Institute", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A2",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "11:00 AM - 12:30 PM",
    room: "Cyber Defense Bunker",
    capacity: 80,
    enrolledCount: 76,
    waitlistCount: 1,
    syllabus: ["AES, RSA & Elliptic Curve Math", "TLS 1.3 Protocol & Forward Secrecy", "X.509 PKI & Certificate Revocation", "Post-Quantum Cryptography Basics"],
    tags: ["Cryptography", "Network Security", "TLS", "Security Core"],
    isLabIncluded: true,
  },
  {
    id: "course-cyb-302",
    code: "CYB302",
    title: "Offensive Security, Penetration Testing & Exploit Dev",
    description: "Buffer overflows, binary exploitation with Ghidra, web vulnerabilities (OWASP Top 10), privilege escalation on Linux/Windows, and red-team operations.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Cybersecurity, Cloud & Ethical Hacking",
    adjacentStreams: ["Computer Science & Engineering"],
    department: { id: "dept-cyb", code: "CYB", name: "Cybersecurity & Cloud" },
    instructor: { name: "Dr. Marcus Vance", title: "Director of Cyber Defense Institute", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B2",
    scheduleDays: "Tue, Thu",
    scheduleTime: "01:30 PM - 03:00 PM",
    room: "Red Team Cyber Range",
    capacity: 65,
    enrolledCount: 64,
    waitlistCount: 7,
    syllabus: ["Stack-Based Buffer Overflows", "Return-Oriented Programming (ROP)", "Advanced SQL Injection & SSRF", "Active Directory Kerberoasting"],
    tags: ["Ethical Hacking", "Pen Testing", "Exploit Dev", "Red Team"],
    isLabIncluded: true,
  },
  {
    id: "course-cyb-405",
    code: "CYB405",
    title: "Zero-Trust Cloud Architecture & DevSecOps",
    description: "Identity and Access Management (IAM), mutual TLS (mTLS), container escape defense, cloud security posture management (CSPM), and automated CI/CD gating.",
    credits: 3,
    difficulty: "Advanced",
    primaryStream: "Cybersecurity, Cloud & Ethical Hacking",
    adjacentStreams: ["Computer Science & Engineering", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-cyb", code: "CYB", name: "Cybersecurity & Cloud" },
    instructor: { name: "Prof. Nina Kowalski", title: "Cloud Security Fellow", avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C2",
    scheduleDays: "Mon, Wed",
    scheduleTime: "02:00 PM - 03:30 PM",
    room: "Cloud Security Hub",
    capacity: 60,
    enrolledCount: 55,
    waitlistCount: 0,
    syllabus: ["Zero-Trust Identity Pillars", "AWS & GCP Least Privilege IAM", "OPA (Open Policy Agent) Rules", "CI/CD Pipeline SAST & DAST Gating"],
    tags: ["Cloud Security", "DevSecOps", "Zero Trust", "AWS"],
  },

  // ─── 9. CIVIL & STRUCTURAL ENGINEERING ───
  {
    id: "course-ce-101",
    code: "CE101",
    title: "Structural Mechanics & Earthquake-Resilient Design",
    description: "Bending moments, shear force distributions, seismic response spectrums, base isolation dampers, and reinforced concrete structural design.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Civil, Environmental & Structural Engineering",
    adjacentStreams: ["Mechanical & Aerospace Engineering", "Chemical Engineering & Nanotechnology"],
    department: { id: "dept-ce", code: "CE", name: "Civil & Environmental" },
    instructor: { name: "Dr. Harish Patel", title: "Dean of Structural Engineering", avatar: "https://images.unsplash.com/photo-1560250097-0b93528c311a?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A1",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "09:00 AM - 10:30 AM",
    room: "Structures Lab 101",
    capacity: 75,
    enrolledCount: 68,
    waitlistCount: 0,
    syllabus: ["Indeterminate Beam Analysis", "Moment Distribution Method", "Seismic Base Isolation Dynamics", "Reinforced Concrete Eurocodes/IS 456"],
    tags: ["Civil", "Structural", "Earthquake Engineering"],
    isLabIncluded: true,
  },

  // ─── 10. CHEMICAL & MATERIAL SCIENCE ───
  {
    id: "course-chem-201",
    code: "CHEM201",
    title: "Nanotechnology, Battery Chemistry & Energy Materials",
    description: "Solid-state electrolyte transport, lithium-ion degradation mechanisms, graphene 2D materials, hydrogen fuel cells, and quantum dots.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Chemical Engineering & Nanotechnology",
    adjacentStreams: ["Electrical, Electronics & VLSI", "Biotechnology, Bioinformatics & Genetics", "Mechanical & Aerospace Engineering"],
    department: { id: "dept-chem", code: "CHEM", name: "Chemical & Materials" },
    instructor: { name: "Dr. Sunita Rao", title: "Chair of Nanomaterials Lab", avatar: "https://images.unsplash.com/photo-1594824813589-58ec71752b07?q=80&w=200&auto=format&fit=crop" },
    slotCode: "B1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "10:45 AM - 12:15 PM",
    room: "Nanotech Cleanroom 1",
    capacity: 60,
    enrolledCount: 54,
    waitlistCount: 0,
    syllabus: ["Intercalation Electrochemistry", "Solid Electrolyte Interphase (SEI)", "2D Graphene & MXene Synthesis", "Fuel Cell Catalyst Kinetics"],
    tags: ["Nanotechnology", "Batteries", "Energy Materials", "Chemistry"],
    isLabIncluded: true,
  },

  // ─── 11. LEGAL STUDIES, CYBER LAW & AI ETHICS ───
  {
    id: "course-law-201",
    code: "LAW201",
    title: "Cyber Law, Digital Privacy & Global AI Governance",
    description: "EU AI Act risk tiers, GDPR compliance, digital sovereignty, algorithmic liability, patent law for AI-generated works, and cross-border data transfer laws.",
    credits: 3,
    difficulty: "Intermediate",
    primaryStream: "Legal Studies, Cyber Law & Tech Policy",
    adjacentStreams: ["Cybersecurity, Cloud & Ethical Hacking", "Artificial Intelligence & Data Science", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-law", code: "LAW", name: "Legal Studies & Policy" },
    instructor: { name: "Prof. Advocate Arjun Nair", title: "Senior Cyber Law Counsel", avatar: "https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Moot Court Hall A",
    capacity: 80,
    enrolledCount: 77,
    waitlistCount: 0,
    syllabus: ["EU AI Act Regulatory Compliance", "GDPR Data Subject Rights & Penalties", "Software IP & Open Source Licensing", "Algorithmic Bias & Corporate Liability"],
    tags: ["Cyber Law", "AI Ethics", "GDPR", "Tech Policy"],
  },

  // ─── 12. MEDICAL SCIENCES & HEALTH INFORMATICS ───
  {
    id: "course-med-201",
    code: "MED201",
    title: "Healthcare Data Architecture, HL7 FHIR & Clinical AI",
    description: "HL7 FHIR clinical data interoperability, HIPAA/DPDP privacy compliance, DICOM medical imaging pipelines, and clinical trial predictive modeling.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Medical Sciences & Health Informatics",
    adjacentStreams: ["Biotechnology, Bioinformatics & Genetics", "Artificial Intelligence & Data Science", "Computer Science & Engineering"],
    department: { id: "dept-med", code: "MED", name: "Medical & Health Informatics" },
    instructor: { name: "Dr. Sarah Jenkins", title: "Chief Medical Information Officer", avatar: "https://images.unsplash.com/photo-1594824813589-58ec71752b07?q=80&w=200&auto=format&fit=crop" },
    slotCode: "C1",
    scheduleDays: "Mon, Wed",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Clinical Informatics Center",
    capacity: 65,
    enrolledCount: 61,
    waitlistCount: 1,
    syllabus: ["HL7 FHIR REST API Standards", "EHR Interoperability & SNOMED CT", "DICOM Medical Image Processing", "Predictive Analytics in ICU Triage"],
    tags: ["Health Tech", "FHIR", "Medical AI", "Clinical Data"],
  },

  // ─── 13. FOUNDATIONAL MATHEMATICS & PHYSICS ───
  {
    id: "course-math-210",
    code: "MATH210",
    title: "Linear Algebra, SVD & Optimization for ML",
    description: "Vector spaces, Singular Value Decomposition (SVD), positive definite matrices, Lagrange multipliers, and convex optimization fundamentals.",
    credits: 4,
    difficulty: "Intermediate",
    primaryStream: "Computer Science & Engineering",
    adjacentStreams: ["Artificial Intelligence & Data Science", "Electrical, Electronics & VLSI", "Business, Fintech & Quantitative Finance"],
    department: { id: "dept-math", code: "MATH", name: "Mathematics & Statistics" },
    instructor: { name: "Dr. Aniruddha Bose", title: "Chair of Pure Mathematics", avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop" },
    slotCode: "A2",
    scheduleDays: "Mon, Wed, Fri",
    scheduleTime: "11:00 AM - 12:30 PM",
    room: "Ramanujan Hall 301",
    capacity: 120,
    enrolledCount: 112,
    waitlistCount: 5,
    syllabus: ["Matrix Decompositions (LU / QR / SVD)", "Eigenvalues & Spectral Theorem", "Convex Sets & Dual Optimization", "Gradient Descent Convergence"],
    tags: ["Mathematics", "Linear Algebra", "Optimization", "Machine Learning"],
  },
  {
    id: "course-phys-301",
    code: "PHYS301",
    title: "Quantum Mechanics & Superconducting Quantum Circuits",
    description: "Schrödinger wave equation, Dirac bra-ket notation, quantum entanglement, Bell inequalities, and Josephson junction superconducting qubits.",
    credits: 4,
    difficulty: "Advanced",
    primaryStream: "Electrical, Electronics & VLSI",
    adjacentStreams: ["Computer Science & Engineering", "Chemical Engineering & Nanotechnology"],
    department: { id: "dept-phys", code: "PHYS", name: "Physics & Astronomy" },
    instructor: { name: "Dr. Richard Feynman-Chair", title: "Fellow of Quantum Physics", avatar: "https://images.unsplash.com/photo-1500648767791-00dcc994a43e?q=80&w=200&auto=format&fit=crop" },
    slotCode: "D1",
    scheduleDays: "Tue, Thu",
    scheduleTime: "03:45 PM - 05:15 PM",
    room: "Quantum Optics Laboratory",
    capacity: 60,
    enrolledCount: 53,
    waitlistCount: 0,
    syllabus: ["Wavefunctions & Hilbert Spaces", "Harmonic Oscillator & Ladder Operators", "Quantum Teleportation & Qubits", "Superconducting Transmon Qubits"],
    tags: ["Quantum", "Physics", "Quantum Computing"],
  }
];

// ✦ HELPER: COMPUTE MATCH LEVEL FOR A STUDENT ✦
export type StreamMatchLevel = "CORE" | "ADJACENT" | "ELECTIVE";

export function getStreamMatchLevel(course: CourseCatalogItem, studentStream?: string): StreamMatchLevel {
  if (!studentStream) return "ELECTIVE";
  
  const normStudent = studentStream.trim().toLowerCase();
  const normPrimary = course.primaryStream.trim().toLowerCase();

  // 1. Direct Core Match
  if (normStudent === normPrimary) {
    return "CORE";
  }

  // 2. Adjacent Match via course.adjacentStreams or STREAM_ADJACENCY_MAP
  const isDirectAdjacent = course.adjacentStreams.some(
    (s) => s.trim().toLowerCase() === normStudent
  );

  const adjacentStreamsForStudent = STREAM_ADJACENCY_MAP[studentStream] || [];
  const isMapAdjacent = adjacentStreamsForStudent.some(
    (s) => s.trim().toLowerCase() === normPrimary
  );

  if (isDirectAdjacent || isMapAdjacent) {
    return "ADJACENT";
  }

  return "ELECTIVE";
}

// ✦ HELPER: FILTER AND RANK COURSES FOR A STUDENT'S STREAM ✦
export function getRecommendedCourses(studentStream?: string): CourseCatalogItem[] {
  if (!studentStream) return EXPANDED_COURSE_CATALOG;

  // Filter and sort: Core first, then Adjacent, then others
  const scored = EXPANDED_COURSE_CATALOG.map((c) => ({
    course: c,
    matchLevel: getStreamMatchLevel(c, studentStream),
  }));

  scored.sort((a, b) => {
    const rankA = a.matchLevel === "CORE" ? 0 : a.matchLevel === "ADJACENT" ? 1 : 2;
    const rankB = b.matchLevel === "CORE" ? 0 : b.matchLevel === "ADJACENT" ? 1 : 2;
    return rankA - rankB;
  });

  return scored.map((s) => s.course);
}
